package com.lit.test1;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnKeyListener;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

public class MainMainActivity extends Activity {

	int keyCode;
	int a = 1;
	TextView text00, text0;
	TextView text1, text2, text3, text4, text5, text6;
	TextView text7, text8, text9, text10, text11, text12;
	TextView text13, text14, text15, text16, text17, text18;
	TextView text19, text20, text21, text22, text23, text24;
	TextView text25, text26, text27, text28, text29, text30;
	TextView text31, text32, text33, text34, text35, text36;
	TextView text37, text38, text39, text40, text41, text42;
	TextView text43, text44, text45, text46, text47, text48;
	TextView text49, text50, text51, text52, text53, text54;
	TextView text55, text56, text57, text58, text59, text60;
	TextView text61, text62, text63, text64, text65, text66;
	TextView text67, text68, text69, text70, text71, text72;
	TextView text73, text74, text75, text76, text77, text78;
	TextView text79, text80, text81, text82, text83, text84;
	TextView text85, text86, text87, text88, text89, text90;
	TextView text91, text92, text93, text94, text95, text96;
	TextView text97, text98, text99, text100, text101;

	EditText edit1;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_mainmain);

		setTitle("HolidayMaster");

		text0 = (TextView) findViewById(R.id.text0);
		text0.setVisibility(View.GONE);
		text1 = (TextView) findViewById(R.id.text1);
		text1.setVisibility(View.GONE);
		text2 = (TextView) findViewById(R.id.text2);
		text2.setVisibility(View.GONE);
		text3 = (TextView) findViewById(R.id.text3);
		text3.setVisibility(View.GONE);
		text4 = (TextView) findViewById(R.id.text4);
		text4.setVisibility(View.GONE);
		text5 = (TextView) findViewById(R.id.text5);
		text5.setVisibility(View.GONE);
		text6 = (TextView) findViewById(R.id.text6);
		text6.setVisibility(View.GONE);
		text7 = (TextView) findViewById(R.id.text7);
		text7.setVisibility(View.GONE);
		text8 = (TextView) findViewById(R.id.text8);
		text8.setVisibility(View.GONE);
		text9 = (TextView) findViewById(R.id.text9);
		text9.setVisibility(View.GONE);
		text10 = (TextView) findViewById(R.id.text10);
		text10.setVisibility(View.GONE);
		text11 = (TextView) findViewById(R.id.text11);
		text11.setVisibility(View.GONE);
		text12 = (TextView) findViewById(R.id.text12);
		text12.setVisibility(View.GONE);
		text13 = (TextView) findViewById(R.id.text13);
		text13.setVisibility(View.GONE);
		text14 = (TextView) findViewById(R.id.text14);
		text14.setVisibility(View.GONE);
		text15 = (TextView) findViewById(R.id.text15);
		text15.setVisibility(View.GONE);
		text16 = (TextView) findViewById(R.id.text16);
		text16.setVisibility(View.GONE);
		text17 = (TextView) findViewById(R.id.text17);
		text17.setVisibility(View.GONE);
		text18 = (TextView) findViewById(R.id.text18);
		text18.setVisibility(View.GONE);
		text19 = (TextView) findViewById(R.id.text19);
		text19.setVisibility(View.GONE);
		text20 = (TextView) findViewById(R.id.text20);
		text20.setVisibility(View.GONE);
		text21 = (TextView) findViewById(R.id.text21);
		text21.setVisibility(View.GONE);
		text22 = (TextView) findViewById(R.id.text22);
		text22.setVisibility(View.GONE);
		text23 = (TextView) findViewById(R.id.text23);
		text23.setVisibility(View.GONE);
		text24 = (TextView) findViewById(R.id.text24);
		text24.setVisibility(View.GONE);
		text25 = (TextView) findViewById(R.id.text25);
		text25.setVisibility(View.GONE);
		text26 = (TextView) findViewById(R.id.text26);
		text26.setVisibility(View.GONE);
		text27 = (TextView) findViewById(R.id.text27);
		text27.setVisibility(View.GONE);
		text28 = (TextView) findViewById(R.id.text28);
		text28.setVisibility(View.GONE);
		text29 = (TextView) findViewById(R.id.text29);
		text29.setVisibility(View.GONE);
		text30 = (TextView) findViewById(R.id.text30);
		text30.setVisibility(View.GONE);
		text31 = (TextView) findViewById(R.id.text31);
		text31.setVisibility(View.GONE);
		text32 = (TextView) findViewById(R.id.text32);
		text32.setVisibility(View.GONE);
		text33 = (TextView) findViewById(R.id.text33);
		text33.setVisibility(View.GONE);
		text34 = (TextView) findViewById(R.id.text34);
		text34.setVisibility(View.GONE);
		text35 = (TextView) findViewById(R.id.text35);
		text35.setVisibility(View.GONE);
		text36 = (TextView) findViewById(R.id.text36);
		text36.setVisibility(View.GONE);
		text37 = (TextView) findViewById(R.id.text37);
		text37.setVisibility(View.GONE);
		text38 = (TextView) findViewById(R.id.text38);
		text38.setVisibility(View.GONE);
		text39 = (TextView) findViewById(R.id.text39);
		text39.setVisibility(View.GONE);
		text40 = (TextView) findViewById(R.id.text40);
		text40.setVisibility(View.GONE);
		text41 = (TextView) findViewById(R.id.text41);
		text41.setVisibility(View.GONE);
		text42 = (TextView) findViewById(R.id.text42);
		text42.setVisibility(View.GONE);
		text43 = (TextView) findViewById(R.id.text43);
		text43.setVisibility(View.GONE);
		text44 = (TextView) findViewById(R.id.text44);
		text44.setVisibility(View.GONE);
		text45 = (TextView) findViewById(R.id.text45);
		text45.setVisibility(View.GONE);
		text46 = (TextView) findViewById(R.id.text46);
		text46.setVisibility(View.GONE);
		text47 = (TextView) findViewById(R.id.text47);
		text47.setVisibility(View.GONE);
		text48 = (TextView) findViewById(R.id.text48);
		text48.setVisibility(View.GONE);
		text49 = (TextView) findViewById(R.id.text49);
		text49.setVisibility(View.GONE);
		text50 = (TextView) findViewById(R.id.text50);
		text50.setVisibility(View.GONE);
		text51 = (TextView) findViewById(R.id.text51);
		text51.setVisibility(View.GONE);
		text52 = (TextView) findViewById(R.id.text52);
		text52.setVisibility(View.GONE);
		text53 = (TextView) findViewById(R.id.text53);
		text53.setVisibility(View.GONE);
		text54 = (TextView) findViewById(R.id.text54);
		text54.setVisibility(View.GONE);
		text55 = (TextView) findViewById(R.id.text55);
		text55.setVisibility(View.GONE);
		text56 = (TextView) findViewById(R.id.text56);
		text56.setVisibility(View.GONE);
		text57 = (TextView) findViewById(R.id.text57);
		text57.setVisibility(View.GONE);
		text58 = (TextView) findViewById(R.id.text58);
		text58.setVisibility(View.GONE);
		text59 = (TextView) findViewById(R.id.text59);
		text59.setVisibility(View.GONE);
		text60 = (TextView) findViewById(R.id.text60);
		text60.setVisibility(View.GONE);
		text61 = (TextView) findViewById(R.id.text61);
		text61.setVisibility(View.GONE);
		text62 = (TextView) findViewById(R.id.text62);
		text62.setVisibility(View.GONE);
		text63 = (TextView) findViewById(R.id.text63);
		text63.setVisibility(View.GONE);
		text64 = (TextView) findViewById(R.id.text64);
		text64.setVisibility(View.GONE);
		text65 = (TextView) findViewById(R.id.text65);
		text65.setVisibility(View.GONE);
		text66 = (TextView) findViewById(R.id.text66);
		text66.setVisibility(View.GONE);
		text67 = (TextView) findViewById(R.id.text67);
		text67.setVisibility(View.GONE);
		text68 = (TextView) findViewById(R.id.text68);
		text68.setVisibility(View.GONE);
		text69 = (TextView) findViewById(R.id.text69);
		text69.setVisibility(View.GONE);
		text70 = (TextView) findViewById(R.id.text70);
		text70.setVisibility(View.GONE);
		text71 = (TextView) findViewById(R.id.text71);
		text71.setVisibility(View.GONE);
		text72 = (TextView) findViewById(R.id.text72);
		text72.setVisibility(View.GONE);
		text73 = (TextView) findViewById(R.id.text73);
		text73.setVisibility(View.GONE);
		text74 = (TextView) findViewById(R.id.text74);
		text74.setVisibility(View.GONE);
		text75 = (TextView) findViewById(R.id.text75);
		text75.setVisibility(View.GONE);
		text76 = (TextView) findViewById(R.id.text76);
		text76.setVisibility(View.GONE);
		text77 = (TextView) findViewById(R.id.text77);
		text77.setVisibility(View.GONE);
		text78 = (TextView) findViewById(R.id.text78);
		text78.setVisibility(View.GONE);
		text79 = (TextView) findViewById(R.id.text79);
		text79.setVisibility(View.GONE);
		text80 = (TextView) findViewById(R.id.text80);
		text80.setVisibility(View.GONE);
		text81 = (TextView) findViewById(R.id.text81);
		text81.setVisibility(View.GONE);
		text82 = (TextView) findViewById(R.id.text82);
		text82.setVisibility(View.GONE);
		text83 = (TextView) findViewById(R.id.text83);
		text83.setVisibility(View.GONE);
		text84 = (TextView) findViewById(R.id.text84);
		text84.setVisibility(View.GONE);
		text85 = (TextView) findViewById(R.id.text85);
		text85.setVisibility(View.GONE);
		text86 = (TextView) findViewById(R.id.text86);
		text86.setVisibility(View.GONE);
		text87 = (TextView) findViewById(R.id.text87);
		text87.setVisibility(View.GONE);
		text88 = (TextView) findViewById(R.id.text88);
		text88.setVisibility(View.GONE);
		text89 = (TextView) findViewById(R.id.text89);
		text89.setVisibility(View.GONE);
		text90 = (TextView) findViewById(R.id.text90);
		text90.setVisibility(View.GONE);
		text91 = (TextView) findViewById(R.id.text91);
		text91.setVisibility(View.GONE);
		text92 = (TextView) findViewById(R.id.text92);
		text92.setVisibility(View.GONE);
		text93 = (TextView) findViewById(R.id.text93);
		text93.setVisibility(View.GONE);
		text94 = (TextView) findViewById(R.id.text94);
		text94.setVisibility(View.GONE);
		text95 = (TextView) findViewById(R.id.text95);
		text95.setVisibility(View.GONE);
		text96 = (TextView) findViewById(R.id.text96);
		text96.setVisibility(View.GONE);
		text97 = (TextView) findViewById(R.id.text97);
		text97.setVisibility(View.GONE);
		text98 = (TextView) findViewById(R.id.text98);
		text98.setVisibility(View.GONE);
		text99 = (TextView) findViewById(R.id.text99);
		text99.setVisibility(View.GONE);
		text100 = (TextView) findViewById(R.id.text100);
		text100.setVisibility(View.GONE);
		text101 = (TextView) findViewById(R.id.text101);
		text101.setVisibility(View.GONE);

		Button button1 = (Button) findViewById(R.id.button1);
		button1.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				onEnter();
			}
		});

		edit1 = (EditText) findViewById(R.id.edit1);
		edit1.setOnKeyListener(new OnKeyListener() {
			@Override
			public boolean onKey(View v, int keyCode, KeyEvent event) {
				if (event.getAction() == KeyEvent.ACTION_DOWN
						&& keyCode == KeyEvent.KEYCODE_ENTER) {
					onEnter();
					return true;
				}
				return false;
			}
		});
	}

	public void onEnter() {
		text0 = (TextView) findViewById(R.id.text0);
		text1 = (TextView) findViewById(R.id.text1);
		edit1 = (EditText) findViewById(R.id.edit1);
		text0.setVisibility(View.VISIBLE);

		text0.setText("検索結果: " + edit1.getText().toString());

		text00 = (TextView) findViewById(R.id.text00);
		text00.setVisibility(View.GONE);
		text1 = (TextView) findViewById(R.id.text1);
		text1.setVisibility(View.GONE);
		text2 = (TextView) findViewById(R.id.text2);
		text2.setVisibility(View.GONE);
		text3 = (TextView) findViewById(R.id.text3);
		text3.setVisibility(View.GONE);
		text4 = (TextView) findViewById(R.id.text4);
		text4.setVisibility(View.GONE);
		text5 = (TextView) findViewById(R.id.text5);
		text5.setVisibility(View.GONE);
		text6 = (TextView) findViewById(R.id.text6);
		text6.setVisibility(View.GONE);
		text7 = (TextView) findViewById(R.id.text7);
		text7.setVisibility(View.GONE);
		text8 = (TextView) findViewById(R.id.text8);
		text8.setVisibility(View.GONE);
		text9 = (TextView) findViewById(R.id.text9);
		text9.setVisibility(View.GONE);
		text10 = (TextView) findViewById(R.id.text10);
		text10.setVisibility(View.GONE);
		text11 = (TextView) findViewById(R.id.text11);
		text11.setVisibility(View.GONE);
		text12 = (TextView) findViewById(R.id.text12);
		text12.setVisibility(View.GONE);
		text13 = (TextView) findViewById(R.id.text13);
		text13.setVisibility(View.GONE);
		text14 = (TextView) findViewById(R.id.text14);
		text14.setVisibility(View.GONE);
		text15 = (TextView) findViewById(R.id.text15);
		text15.setVisibility(View.GONE);
		text16 = (TextView) findViewById(R.id.text16);
		text16.setVisibility(View.GONE);
		text17 = (TextView) findViewById(R.id.text17);
		text17.setVisibility(View.GONE);
		text18 = (TextView) findViewById(R.id.text18);
		text18.setVisibility(View.GONE);
		text19 = (TextView) findViewById(R.id.text19);
		text19.setVisibility(View.GONE);
		text20 = (TextView) findViewById(R.id.text20);
		text20.setVisibility(View.GONE);
		text21 = (TextView) findViewById(R.id.text21);
		text21.setVisibility(View.GONE);
		text22 = (TextView) findViewById(R.id.text22);
		text22.setVisibility(View.GONE);
		text23 = (TextView) findViewById(R.id.text23);
		text23.setVisibility(View.GONE);
		text24 = (TextView) findViewById(R.id.text24);
		text24.setVisibility(View.GONE);
		text25 = (TextView) findViewById(R.id.text25);
		text25.setVisibility(View.GONE);
		text26 = (TextView) findViewById(R.id.text26);
		text26.setVisibility(View.GONE);
		text27 = (TextView) findViewById(R.id.text27);
		text27.setVisibility(View.GONE);
		text28 = (TextView) findViewById(R.id.text28);
		text28.setVisibility(View.GONE);
		text29 = (TextView) findViewById(R.id.text29);
		text29.setVisibility(View.GONE);
		text30 = (TextView) findViewById(R.id.text30);
		text30.setVisibility(View.GONE);
		text31 = (TextView) findViewById(R.id.text31);
		text31.setVisibility(View.GONE);
		text32 = (TextView) findViewById(R.id.text32);
		text32.setVisibility(View.GONE);
		text33 = (TextView) findViewById(R.id.text33);
		text33.setVisibility(View.GONE);
		text34 = (TextView) findViewById(R.id.text34);
		text34.setVisibility(View.GONE);
		text35 = (TextView) findViewById(R.id.text35);
		text35.setVisibility(View.GONE);
		text36 = (TextView) findViewById(R.id.text36);
		text36.setVisibility(View.GONE);
		text37 = (TextView) findViewById(R.id.text37);
		text37.setVisibility(View.GONE);
		text38 = (TextView) findViewById(R.id.text38);
		text38.setVisibility(View.GONE);
		text39 = (TextView) findViewById(R.id.text39);
		text39.setVisibility(View.GONE);
		text40 = (TextView) findViewById(R.id.text40);
		text40.setVisibility(View.GONE);
		text41 = (TextView) findViewById(R.id.text41);
		text41.setVisibility(View.GONE);
		text42 = (TextView) findViewById(R.id.text42);
		text42.setVisibility(View.GONE);
		text43 = (TextView) findViewById(R.id.text43);
		text43.setVisibility(View.GONE);
		text44 = (TextView) findViewById(R.id.text44);
		text44.setVisibility(View.GONE);
		text45 = (TextView) findViewById(R.id.text45);
		text45.setVisibility(View.GONE);
		text46 = (TextView) findViewById(R.id.text46);
		text46.setVisibility(View.GONE);
		text47 = (TextView) findViewById(R.id.text47);
		text47.setVisibility(View.GONE);
		text48 = (TextView) findViewById(R.id.text48);
		text48.setVisibility(View.GONE);
		text49 = (TextView) findViewById(R.id.text49);
		text49.setVisibility(View.GONE);
		text50 = (TextView) findViewById(R.id.text50);
		text50.setVisibility(View.GONE);
		text51 = (TextView) findViewById(R.id.text51);
		text51.setVisibility(View.GONE);
		text52 = (TextView) findViewById(R.id.text52);
		text52.setVisibility(View.GONE);
		text53 = (TextView) findViewById(R.id.text53);
		text53.setVisibility(View.GONE);
		text54 = (TextView) findViewById(R.id.text54);
		text54.setVisibility(View.GONE);
		text55 = (TextView) findViewById(R.id.text55);
		text55.setVisibility(View.GONE);
		text56 = (TextView) findViewById(R.id.text56);
		text56.setVisibility(View.GONE);
		text57 = (TextView) findViewById(R.id.text57);
		text57.setVisibility(View.GONE);
		text58 = (TextView) findViewById(R.id.text58);
		text58.setVisibility(View.GONE);
		text59 = (TextView) findViewById(R.id.text59);
		text59.setVisibility(View.GONE);
		text60 = (TextView) findViewById(R.id.text60);
		text60.setVisibility(View.GONE);
		text61 = (TextView) findViewById(R.id.text61);
		text61.setVisibility(View.GONE);
		text62 = (TextView) findViewById(R.id.text62);
		text62.setVisibility(View.GONE);
		text63 = (TextView) findViewById(R.id.text63);
		text63.setVisibility(View.GONE);
		text64 = (TextView) findViewById(R.id.text64);
		text64.setVisibility(View.GONE);
		text65 = (TextView) findViewById(R.id.text65);
		text65.setVisibility(View.GONE);
		text66 = (TextView) findViewById(R.id.text66);
		text66.setVisibility(View.GONE);
		text67 = (TextView) findViewById(R.id.text67);
		text67.setVisibility(View.GONE);
		text68 = (TextView) findViewById(R.id.text68);
		text68.setVisibility(View.GONE);
		text69 = (TextView) findViewById(R.id.text69);
		text69.setVisibility(View.GONE);
		text70 = (TextView) findViewById(R.id.text70);
		text70.setVisibility(View.GONE);
		text71 = (TextView) findViewById(R.id.text71);
		text71.setVisibility(View.GONE);
		text72 = (TextView) findViewById(R.id.text72);
		text72.setVisibility(View.GONE);
		text73 = (TextView) findViewById(R.id.text73);
		text73.setVisibility(View.GONE);
		text74 = (TextView) findViewById(R.id.text74);
		text74.setVisibility(View.GONE);
		text75 = (TextView) findViewById(R.id.text75);
		text75.setVisibility(View.GONE);
		text76 = (TextView) findViewById(R.id.text76);
		text76.setVisibility(View.GONE);
		text77 = (TextView) findViewById(R.id.text77);
		text77.setVisibility(View.GONE);
		text78 = (TextView) findViewById(R.id.text78);
		text78.setVisibility(View.GONE);
		text79 = (TextView) findViewById(R.id.text79);
		text79.setVisibility(View.GONE);
		text80 = (TextView) findViewById(R.id.text80);
		text80.setVisibility(View.GONE);
		text81 = (TextView) findViewById(R.id.text81);
		text81.setVisibility(View.GONE);
		text82 = (TextView) findViewById(R.id.text82);
		text82.setVisibility(View.GONE);
		text83 = (TextView) findViewById(R.id.text83);
		text83.setVisibility(View.GONE);
		text84 = (TextView) findViewById(R.id.text84);
		text84.setVisibility(View.GONE);
		text85 = (TextView) findViewById(R.id.text85);
		text85.setVisibility(View.GONE);
		text86 = (TextView) findViewById(R.id.text86);
		text86.setVisibility(View.GONE);
		text87 = (TextView) findViewById(R.id.text87);
		text87.setVisibility(View.GONE);
		text88 = (TextView) findViewById(R.id.text88);
		text88.setVisibility(View.GONE);
		text89 = (TextView) findViewById(R.id.text89);
		text89.setVisibility(View.GONE);
		text90 = (TextView) findViewById(R.id.text90);
		text90.setVisibility(View.GONE);
		text91 = (TextView) findViewById(R.id.text91);
		text91.setVisibility(View.GONE);
		text92 = (TextView) findViewById(R.id.text92);
		text92.setVisibility(View.GONE);
		text93 = (TextView) findViewById(R.id.text93);
		text93.setVisibility(View.GONE);
		text94 = (TextView) findViewById(R.id.text94);
		text94.setVisibility(View.GONE);
		text95 = (TextView) findViewById(R.id.text95);
		text95.setVisibility(View.GONE);
		text96 = (TextView) findViewById(R.id.text96);
		text96.setVisibility(View.GONE);
		text97 = (TextView) findViewById(R.id.text97);
		text97.setVisibility(View.GONE);
		text98 = (TextView) findViewById(R.id.text98);
		text98.setVisibility(View.GONE);
		text99 = (TextView) findViewById(R.id.text99);
		text99.setVisibility(View.GONE);
		text100 = (TextView) findViewById(R.id.text100);
		text100.setVisibility(View.GONE);
		text101 = (TextView) findViewById(R.id.text101);
		text101.setVisibility(View.GONE);

		if (edit1.getText().toString().equals("cafe")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Eggs 'n Things 原宿店");
			text2.setVisibility(View.VISIBLE);
			text2.setText("カルビープラス 東京駅店");
			text3.setVisibility(View.VISIBLE);
			text3.setText("珈琲天国");
			text4.setVisibility(View.VISIBLE);
			text4.setText("cafe ordinaire");
			text5.setVisibility(View.VISIBLE);
			text5.setText("ブック・カフェ　槐多");
			text6.setVisibility(View.VISIBLE);
			text6.setText("CAFE RASHIKU");
			text7.setVisibility(View.VISIBLE);
			text7.setText("Brooklyn Parlor");
			text8.setVisibility(View.VISIBLE);
			text8.setText("CAT'S CRADLE");
			text9.setVisibility(View.VISIBLE);
			text9.setText("Dexee Diner");
			text10.setVisibility(View.VISIBLE);
			text10.setText("Bibliotheque");
			text11.setVisibility(View.VISIBLE);
			text11.setText("MOTOYA Book・Cafe・Gallery");
			text12.setVisibility(View.VISIBLE);
			text12.setText("Library Lounge THESE");
			text13.setVisibility(View.VISIBLE);
			text13.setText("Rainy Day Bookstore & Cafe");
			text14.setVisibility(View.VISIBLE);
			text14.setText("TSUTAYA TOKYO ROPPOBNGI");
			text15.setVisibility(View.VISIBLE);
			text15.setText("ARGO");
			text16.setVisibility(View.VISIBLE);
			text16.setText("combine");
			text17.setVisibility(View.VISIBLE);
			text17.setText("LA・VITA");
			text18.setVisibility(View.VISIBLE);
			text18.setText("ホノルルコーヒー");
			text19.setVisibility(View.VISIBLE);
			text19.setText("クリスピー・クリーム・ドーナツ 新宿サザンテラス店");
			text20.setVisibility(View.VISIBLE);
			text20.setText("PANINO VINO");
			text21.setVisibility(View.VISIBLE);
			text21.setText("Deux Anges");
			text22.setVisibility(View.VISIBLE);
			text22.setText("Brasserie cafe' Le Conte");
			text23.setVisibility(View.VISIBLE);
			text23.setText("cafe table TERRACE");
			text24.setVisibility(View.VISIBLE);
			text24.setText("Dining cafe HOME");
			text25.setVisibility(View.VISIBLE);
			text25.setText("NALU cafe omotesando");
			text26.setVisibility(View.VISIBLE);
			text26.setText("TOWN DESIGN CAFE Jingumae");
			text27.setVisibility(View.VISIBLE);
			text27.setText("STaiR");
			text28.setVisibility(View.VISIBLE);
			text28.setText("C’s fort");
			text29.setVisibility(View.VISIBLE);
			text29.setText("ジェイエスバーガーズカフェ 原宿店");
			text30.setVisibility(View.VISIBLE);
			text30.setText("RFECTOIRE");
			text31.setVisibility(View.VISIBLE);
			text31.setText("THE GREAT BURGER");
			text32.setVisibility(View.VISIBLE);
			text32.setText("uzna omom");
			text33.setVisibility(View.VISIBLE);
			text33.setText("montoak");
			text34.setVisibility(View.VISIBLE);
			text34.setText("エコファームカフェ 632");
			text35.setVisibility(View.VISIBLE);
			text35.setText("アマーク　ド　パラディ");
			text36.setVisibility(View.VISIBLE);
			text36.setText("クレープリー　アルション");
			text37.setVisibility(View.VISIBLE);
			text37.setText("Planet3rd");
			text38.setVisibility(View.VISIBLE);
			text38.setText("ベリーファンシー");
			text39.setVisibility(View.VISIBLE);
			text39.setText("北極星");
			text40.setVisibility(View.VISIBLE);
			text40.setText("COCOASHOP　AKAI TORI");
			text41.setVisibility(View.VISIBLE);
			text41.setText("リバーカフェ");
			text42.setVisibility(View.VISIBLE);
			text42.setText("太陽の塔");
			text43.setVisibility(View.VISIBLE);
			text43.setText("RIVER CAFE");
			text44.setVisibility(View.VISIBLE);
			text44.setText("ARABIYA");
			text45.setVisibility(View.VISIBLE);
			text45.setText("TABLES CAFE");
			text46.setVisibility(View.VISIBLE);
			text46.setText("和カフェyusoshi chano-ma なんばマルイ店");
			text47.setVisibility(View.VISIBLE);
			text47.setText("STANDARD BOOKSTORE");
			text48.setVisibility(View.VISIBLE);
			text48.setText("BUTTERFLY");
			text49.setVisibility(View.VISIBLE);
			text49.setText("野菜直売 Green Cafe");
			text50.setVisibility(View.VISIBLE);
			text50.setText("cafe The Plant Room");
			text51.setVisibility(View.VISIBLE);
			text51.setText("MINGUS");
			text52.setVisibility(View.VISIBLE);
			text52.setText("ANTICO CAFFE ALAVIS");
			text53.setVisibility(View.VISIBLE);
			text53.setText("LOBBY CAFE FASCINO");
			text54.setVisibility(View.VISIBLE);
			text54.setText("Anna Colors COFFEE");
			text55.setVisibility(View.VISIBLE);
			text55.setText("Cafe de la Paix");
			text56.setVisibility(View.VISIBLE);
			text56.setText("UMIYA CAFE westpoint");
			text57.setVisibility(View.VISIBLE);
			text57.setText("NOON+CAFE");
			text58.setVisibility(View.VISIBLE);
			text58.setText("Factory Cafe");
			text59.setVisibility(View.VISIBLE);
			text59.setText("WIRED CAFE 梅田NU chayamachi店");
			text60.setVisibility(View.VISIBLE);
			text60.setText("HANDS CAFE");
			text61.setVisibility(View.VISIBLE);
			text61.setText("ブラザーズカフェ 梅田オーパ店");
			text62.setVisibility(View.VISIBLE);
			text62.setText("The Grand Cafe");
			text63.setVisibility(View.VISIBLE);
			text63.setText("スーホルム カフェ+ダイニング");
			text64.setVisibility(View.VISIBLE);
			text64.setText("RIVER CAFE");
			text65.setVisibility(View.VISIBLE);
			text65.setText("雪ノ下工房");
			text66.setVisibility(View.VISIBLE);
			text66.setText("Marble");
			text67.setVisibility(View.VISIBLE);
			text67.setText("ノードカフェ");
			text68.setVisibility(View.VISIBLE);
			text68.setText("colors");
			text69.setVisibility(View.VISIBLE);
			text69.setText("PARTAGE");
			text70.setVisibility(View.VISIBLE);
			text70.setText("Cafeゆう 梅田店");
			text71.setVisibility(View.VISIBLE);
			text71.setText("Hug Cafe");
			text72.setVisibility(View.VISIBLE);
			text72.setText("美山cafe 梅三小路店");
			text73.setVisibility(View.VISIBLE);
			text73.setText("agmo on");
			text74.setVisibility(View.VISIBLE);
			text74.setText("トリトンカフェ 梅田店");
			text75.setVisibility(View.VISIBLE);
			text75.setText("J'adore Chayamachi");
			text76.setVisibility(View.VISIBLE);
			text76.setText("DOWNSTAIRS COFFEE");
			text77.setVisibility(View.VISIBLE);
			text77.setText("SOLVIVA");
			text78.setVisibility(View.VISIBLE);
			text78.setText("Monsoon Cafe");
			text79.setVisibility(View.VISIBLE);
			text79.setText("ツェープラス");
			text80.setVisibility(View.VISIBLE);
			text80.setText("miss evans");
			text81.setVisibility(View.VISIBLE);
			text81.setText("DJANGO");
			text82.setVisibility(View.VISIBLE);
			text82.setText("j.s. pancake cafe");
			text83.setVisibility(View.VISIBLE);
			text83.setText("メゾンカイザー あべのハルカス近鉄本店 タワー館");
			text84.setVisibility(View.VISIBLE);
			text84.setText("Oval");
			text85.setVisibility(View.VISIBLE);
			text85.setText("aureole d’ange");

		} else if (edit1.getText().toString().equals("カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Eggs 'n Things 原宿店");
			text2.setVisibility(View.VISIBLE);
			text2.setText("カルビープラス 東京駅店");
			text3.setVisibility(View.VISIBLE);
			text3.setText("珈琲天国");
			text4.setVisibility(View.VISIBLE);
			text4.setText("cafe ordinaire");
			text5.setVisibility(View.VISIBLE);
			text5.setText("ブック・カフェ　槐多");
			text6.setVisibility(View.VISIBLE);
			text6.setText("CAFE RASHIKU");
			text7.setVisibility(View.VISIBLE);
			text7.setText("Brooklyn Parlor");
			text8.setVisibility(View.VISIBLE);
			text8.setText("CAT'S CRADLE");
			text9.setVisibility(View.VISIBLE);
			text9.setText("Dexee Diner");
			text10.setVisibility(View.VISIBLE);
			text10.setText("Bibliotheque");
			text11.setVisibility(View.VISIBLE);
			text11.setText("MOTOYA Book・Cafe・Gallery");
			text12.setVisibility(View.VISIBLE);
			text12.setText("Library Lounge THESE");
			text13.setVisibility(View.VISIBLE);
			text13.setText("Rainy Day Bookstore & Cafe");
			text14.setVisibility(View.VISIBLE);
			text14.setText("TSUTAYA TOKYO ROPPOBNGI");
			text15.setVisibility(View.VISIBLE);
			text15.setText("ARGO");
			text16.setVisibility(View.VISIBLE);
			text16.setText("combine");
			text17.setVisibility(View.VISIBLE);
			text17.setText("LA・VITA");
			text18.setVisibility(View.VISIBLE);
			text18.setText("ホノルルコーヒー");
			text19.setVisibility(View.VISIBLE);
			text19.setText("クリスピー・クリーム・ドーナツ 新宿サザンテラス店");
			text20.setVisibility(View.VISIBLE);
			text20.setText("PANINO VINO");
			text21.setVisibility(View.VISIBLE);
			text21.setText("Deux Anges");
			text22.setVisibility(View.VISIBLE);
			text22.setText("Brasserie cafe' Le Conte");
			text23.setVisibility(View.VISIBLE);
			text23.setText("cafe table TERRACE");
			text24.setVisibility(View.VISIBLE);
			text24.setText("Dining cafe HOME");
			text25.setVisibility(View.VISIBLE);
			text25.setText("NALU cafe omotesando");
			text26.setVisibility(View.VISIBLE);
			text26.setText("TOWN DESIGN CAFE Jingumae");
			text27.setVisibility(View.VISIBLE);
			text27.setText("STaiR");
			text28.setVisibility(View.VISIBLE);
			text28.setText("C’s fort");
			text29.setVisibility(View.VISIBLE);
			text29.setText("ジェイエスバーガーズカフェ 原宿店");
			text30.setVisibility(View.VISIBLE);
			text30.setText("RFECTOIRE");
			text31.setVisibility(View.VISIBLE);
			text31.setText("THE GREAT BURGER");
			text32.setVisibility(View.VISIBLE);
			text32.setText("uzna omom");
			text33.setVisibility(View.VISIBLE);
			text33.setText("montoak");
			text34.setVisibility(View.VISIBLE);
			text34.setText("エコファームカフェ 632");
			text35.setVisibility(View.VISIBLE);
			text35.setText("アマーク　ド　パラディ");
			text36.setVisibility(View.VISIBLE);
			text36.setText("クレープリー　アルション");
			text37.setVisibility(View.VISIBLE);
			text37.setText("Planet3rd");
			text38.setVisibility(View.VISIBLE);
			text38.setText("ベリーファンシー");
			text39.setVisibility(View.VISIBLE);
			text39.setText("北極星");
			text40.setVisibility(View.VISIBLE);
			text40.setText("COCOASHOP　AKAI TORI");
			text41.setVisibility(View.VISIBLE);
			text41.setText("リバーカフェ");
			text42.setVisibility(View.VISIBLE);
			text42.setText("太陽の塔");
			text43.setVisibility(View.VISIBLE);
			text43.setText("RIVER CAFE");
			text44.setVisibility(View.VISIBLE);
			text44.setText("ARABIYA");
			text45.setVisibility(View.VISIBLE);
			text45.setText("TABLES CAFE");
			text46.setVisibility(View.VISIBLE);
			text46.setText("和カフェyusoshi chano-ma なんばマルイ店");
			text47.setVisibility(View.VISIBLE);
			text47.setText("STANDARD BOOKSTORE");
			text48.setVisibility(View.VISIBLE);
			text48.setText("BUTTERFLY");
			text49.setVisibility(View.VISIBLE);
			text49.setText("野菜直売 Green Cafe");
			text50.setVisibility(View.VISIBLE);
			text50.setText("cafe The Plant Room");
			text51.setVisibility(View.VISIBLE);
			text51.setText("MINGUS");
			text52.setVisibility(View.VISIBLE);
			text52.setText("ANTICO CAFFE ALAVIS");
			text53.setVisibility(View.VISIBLE);
			text53.setText("LOBBY CAFE FASCINO");
			text54.setVisibility(View.VISIBLE);
			text54.setText("Anna Colors COFFEE");
			text55.setVisibility(View.VISIBLE);
			text55.setText("Cafe de la Paix");
			text56.setVisibility(View.VISIBLE);
			text56.setText("UMIYA CAFE westpoint");
			text57.setVisibility(View.VISIBLE);
			text57.setText("NOON+CAFE");
			text58.setVisibility(View.VISIBLE);
			text58.setText("Factory Cafe");
			text59.setVisibility(View.VISIBLE);
			text59.setText("WIRED CAFE 梅田NU chayamachi店");
			text60.setVisibility(View.VISIBLE);
			text60.setText("HANDS CAFE");
			text61.setVisibility(View.VISIBLE);
			text61.setText("ブラザーズカフェ 梅田オーパ店");
			text62.setVisibility(View.VISIBLE);
			text62.setText("The Grand Cafe");
			text63.setVisibility(View.VISIBLE);
			text63.setText("スーホルム カフェ+ダイニング");
			text64.setVisibility(View.VISIBLE);
			text64.setText("RIVER CAFE");
			text65.setVisibility(View.VISIBLE);
			text65.setText("雪ノ下工房");
			text66.setVisibility(View.VISIBLE);
			text66.setText("Marble");
			text67.setVisibility(View.VISIBLE);
			text67.setText("ノードカフェ");
			text68.setVisibility(View.VISIBLE);
			text68.setText("colors");
			text69.setVisibility(View.VISIBLE);
			text69.setText("PARTAGE");
			text70.setVisibility(View.VISIBLE);
			text70.setText("Cafeゆう 梅田店");
			text71.setVisibility(View.VISIBLE);
			text71.setText("Hug Cafe");
			text72.setVisibility(View.VISIBLE);
			text72.setText("美山cafe 梅三小路店");
			text73.setVisibility(View.VISIBLE);
			text73.setText("agmo on");
			text74.setVisibility(View.VISIBLE);
			text74.setText("トリトンカフェ 梅田店");
			text75.setVisibility(View.VISIBLE);
			text75.setText("J'adore Chayamachi");
			text76.setVisibility(View.VISIBLE);
			text76.setText("DOWNSTAIRS COFFEE");
			text77.setVisibility(View.VISIBLE);
			text77.setText("SOLVIVA");
			text78.setVisibility(View.VISIBLE);
			text78.setText("Monsoon Cafe");
			text79.setVisibility(View.VISIBLE);
			text79.setText("ツェープラス");
			text80.setVisibility(View.VISIBLE);
			text80.setText("miss evans");
			text81.setVisibility(View.VISIBLE);
			text81.setText("DJANGO");
			text82.setVisibility(View.VISIBLE);
			text82.setText("j.s. pancake cafe");
			text83.setVisibility(View.VISIBLE);
			text83.setText("メゾンカイザー あべのハルカス近鉄本店 タワー館");
			text84.setVisibility(View.VISIBLE);
			text84.setText("Oval");
			text85.setVisibility(View.VISIBLE);
			text85.setText("aureole d’ange");
			/*
			 * text86.setVisibility(View.VISIBLE); text86.setText("");
			 * text87.setVisibility(View.VISIBLE); text87.setText("");
			 * text88.setVisibility(View.VISIBLE); text88.setText("");
			 * text89.setVisibility(View.VISIBLE); text89.setText("");
			 * text90.setVisibility(View.VISIBLE); text90.setText("");
			 */

		} else if (edit1.getText().toString().equals("shopping mall")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("東京ソラマチ");
			text2.setVisibility(View.VISIBLE);
			text2.setText("恵比寿ガーデンプレイス");
			text3.setVisibility(View.VISIBLE);
			text3.setText("ダイバーシティ東京 プラザ");
			text4.setVisibility(View.VISIBLE);
			text4.setText("汐留シオサイト5区イタリア街");
			text5.setVisibility(View.VISIBLE);
			text5.setText("赤坂サカス");
			text6.setVisibility(View.VISIBLE);
			text6.setText("カレッタ汐留");
			text7.setVisibility(View.VISIBLE);
			text7.setText("HEP FIVE");
			text8.setVisibility(View.VISIBLE);
			text8.setText("なんばパークス");

		} else if (edit1.getText().toString().equals("ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("東京ソラマチ");
			text2.setVisibility(View.VISIBLE);
			text2.setText("恵比寿ガーデンプレイス");
			text3.setVisibility(View.VISIBLE);
			text3.setText("ダイバーシティ東京 プラザ");
			text4.setVisibility(View.VISIBLE);
			text4.setText("汐留シオサイト5区イタリア街");
			text5.setVisibility(View.VISIBLE);
			text5.setText("赤坂サカス");
			text6.setVisibility(View.VISIBLE);
			text6.setText("カレッタ汐留");
			text7.setVisibility(View.VISIBLE);
			text7.setText("HEP FIVE");
			text8.setVisibility(View.VISIBLE);
			text8.setText("なんばパークス");
			text9.setVisibility(View.VISIBLE);
			text9.setText("あべの Q's MALL");

		} else if (edit1.getText().toString().equals("美術館")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("国立新美術館");
			text2.setVisibility(View.VISIBLE);
			text2.setText("森美術館");
			text3.setVisibility(View.VISIBLE);
			text3.setText("国立国際美術館");

		} else if (edit1.getText().toString().equals("東京")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Eggs 'n Things 原宿店");
			text2.setVisibility(View.VISIBLE);
			text2.setText("カルビープラス 東京駅店");
			text3.setVisibility(View.VISIBLE);
			text3.setText("珈琲天国");
			text4.setVisibility(View.VISIBLE);
			text4.setText("cafe ordinaire");
			text5.setVisibility(View.VISIBLE);
			text5.setText("ブック・カフェ　槐多");
			text6.setVisibility(View.VISIBLE);
			text6.setText("CAFE RASHIKU");
			text7.setVisibility(View.VISIBLE);
			text7.setText("Brooklyn Parlor");
			text8.setVisibility(View.VISIBLE);
			text8.setText("CAT'S CRADLE");
			text9.setVisibility(View.VISIBLE);
			text9.setText("Dexee Diner");
			text10.setVisibility(View.VISIBLE);
			text10.setText("Bibliotheque");
			text11.setVisibility(View.VISIBLE);
			text11.setText("MOTOYA Book・Cafe・Gallery");
			text12.setVisibility(View.VISIBLE);
			text12.setText("Library Lounge THESE");
			text13.setVisibility(View.VISIBLE);
			text13.setText("Rainy Day Bookstore & Cafe");
			text14.setVisibility(View.VISIBLE);
			text14.setText("TSUTAYA TOKYO ROPPOBNGI");
			text15.setVisibility(View.VISIBLE);
			text15.setText("ARGO");
			text16.setVisibility(View.VISIBLE);
			text16.setText("combine");
			text17.setVisibility(View.VISIBLE);
			text17.setText("LA・VITA");
			text18.setVisibility(View.VISIBLE);
			text18.setText("ホノルルコーヒー");
			text19.setVisibility(View.VISIBLE);
			text19.setText("クリスピー・クリーム・ドーナツ 新宿サザンテラス店");
			text20.setVisibility(View.VISIBLE);
			text20.setText("PANINO VINO");
			text21.setVisibility(View.VISIBLE);
			text21.setText("Deux Anges");
			text22.setVisibility(View.VISIBLE);
			text22.setText("Brasserie cafe' Le Conte");
			text23.setVisibility(View.VISIBLE);
			text23.setText("cafe table TERRACE");
			text24.setVisibility(View.VISIBLE);
			text24.setText("Dining cafe HOME");
			text25.setVisibility(View.VISIBLE);
			text25.setText("NALU cafe omotesando");
			text26.setVisibility(View.VISIBLE);
			text26.setText("TOWN DESIGN CAFE Jingumae");
			text27.setVisibility(View.VISIBLE);
			text27.setText("STaiR");
			text28.setVisibility(View.VISIBLE);
			text28.setText("C’s fort");
			text29.setVisibility(View.VISIBLE);
			text29.setText("ジェイエスバーガーズカフェ 原宿店");
			text30.setVisibility(View.VISIBLE);
			text30.setText("RFECTOIRE");
			text31.setVisibility(View.VISIBLE);
			text31.setText("THE GREAT BURGER");
			text32.setVisibility(View.VISIBLE);
			text32.setText("uzna omom");
			text33.setVisibility(View.VISIBLE);
			text33.setText("montoak");
			text34.setVisibility(View.VISIBLE);
			text34.setText("エコファームカフェ 632");
			text35.setVisibility(View.VISIBLE);
			text35.setText("東京ソラマチ");
			text36.setVisibility(View.VISIBLE);
			text36.setText("恵比寿ガーデンプレイス");
			text37.setVisibility(View.VISIBLE);
			text37.setText("ダイバーシティ東京 プラザ");
			text38.setVisibility(View.VISIBLE);
			text38.setText("汐留シオサイト5区イタリア街");
			text39.setVisibility(View.VISIBLE);
			text39.setText("赤坂サカス");
			text40.setVisibility(View.VISIBLE);
			text40.setText("カレッタ汐留");
			text41.setVisibility(View.VISIBLE);
			text41.setText("国立新美術館");
			text42.setVisibility(View.VISIBLE);
			text42.setText("森美術館");

		} else if (edit1.getText().toString().equals("新宿")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Brooklyn Parlor");
			text2.setVisibility(View.VISIBLE);
			text2.setText("CAT'S CRADLE");

		} else if (edit1.getText().toString().equals("新宿　カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Brooklyn Parlor");
			text2.setVisibility(View.VISIBLE);
			text2.setText("CAT'S CRADLE");

		} else if (edit1.getText().toString().equals("渋谷")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Eggs 'n Things 原宿店");
			text2.setVisibility(View.VISIBLE);
			text2.setText("渋谷ヒカリエ");
			text3.setVisibility(View.VISIBLE);
			text3.setText("恵比寿ガーデンプレイス");
			text4.setVisibility(View.VISIBLE);
			text4.setText("Dexee Diner");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Bibliotheque");
			text6.setVisibility(View.VISIBLE);
			text6.setText("MOTOYA Book・Cafe・Gallery");
			text7.setVisibility(View.VISIBLE);
			text7.setText("表参道ヒルズ");
			text8.setVisibility(View.VISIBLE);
			text8.setText("クリスピー・クリーム・ドーナツ 新宿サザンテラス店");
			text9.setVisibility(View.VISIBLE);
			text9.setText("PANINO VINO");
			text10.setVisibility(View.VISIBLE);
			text10.setText("Deux Anges");
			text11.setVisibility(View.VISIBLE);
			text11.setText("Dining cafe HOME");
			text12.setVisibility(View.VISIBLE);
			text12.setText("NALU cafe omotesando");
			text13.setVisibility(View.VISIBLE);
			text13.setText("TOWN DESIGN CAFE Jingumae");
			text14.setVisibility(View.VISIBLE);
			text14.setText("ジェイエスバーガーズカフェ 原宿店");
			text15.setVisibility(View.VISIBLE);
			text15.setText("RFECTOIRE");
			text16.setVisibility(View.VISIBLE);
			text16.setText("THE GREAT BURGER");
			text17.setVisibility(View.VISIBLE);
			text17.setText("uzna omom");
			text18.setVisibility(View.VISIBLE);
			text18.setText("montoak");
			text19.setVisibility(View.VISIBLE);
			text19.setText("エコファームカフェ 632");

		} else if (edit1.getText().toString().equals("渋谷 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Eggs 'n Things 原宿店");
			text2.setVisibility(View.VISIBLE);
			text2.setText("Dexee Diner");
			text3.setVisibility(View.VISIBLE);
			text3.setText("Bibliotheque");
			text4.setVisibility(View.VISIBLE);
			text4.setText("MOTOYA Book・Cafe・Gallery");
			text5.setVisibility(View.VISIBLE);
			text5.setText("クリスピー・クリーム・ドーナツ 新宿サザンテラス店");
			text6.setVisibility(View.VISIBLE);
			text6.setText("PANINO VINO");
			text7.setVisibility(View.VISIBLE);
			text7.setText("Deux Anges");
			text8.setVisibility(View.VISIBLE);
			text8.setText("Dining cafe HOME");
			text9.setVisibility(View.VISIBLE);
			text9.setText("NALU cafe omotesando");
			text10.setVisibility(View.VISIBLE);
			text10.setText("TOWN DESIGN CAFE Jingumae");
			text11.setVisibility(View.VISIBLE);
			text11.setText("ジェイエスバーガーズカフェ 原宿店");
			text12.setVisibility(View.VISIBLE);
			text12.setText("RFECTOIRE");
			text13.setVisibility(View.VISIBLE);
			text13.setText("THE GREAT BURGER");
			text14.setVisibility(View.VISIBLE);
			text14.setText("uzna omom");
			text15.setVisibility(View.VISIBLE);
			text15.setText("montoak");
			text16.setVisibility(View.VISIBLE);
			text16.setText("エコファームカフェ 632");

		} else if (edit1.getText().toString().equals("世田谷")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("cafe ordinaire");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ブック・カフェ　槐多");
			text3.setVisibility(View.VISIBLE);
			text3.setText("CAFE RASHIKU");

		} else if (edit1.getText().toString().equals("世田谷 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("cafe ordinaire");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ブック・カフェ　槐多");
			text3.setVisibility(View.VISIBLE);
			text3.setText("CAFE RASHIKU");

		} else if (edit1.getText().toString().equals("江東区")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("日本未来科学館");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ダイバーシティ東京 プラザ");
			text3.setVisibility(View.VISIBLE);
			text3.setText("ホノルルコーヒー");

		} else if (edit1.getText().toString().equals("江東区 ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("ダイバーシティ東京 プラザ");

		} else if (edit1.getText().toString().equals("江東区　カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("ホノルルコーヒー");

		} else if (edit1.getText().toString().equals("目黒")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("combine");
			text2.setVisibility(View.VISIBLE);
			text2.setText("LA・VITA");

		} else if (edit1.getText().toString().equals("目黒 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("combine");
			text2.setVisibility(View.VISIBLE);
			text2.setText("LA・VITA");

		} else if (edit1.getText().toString().equals("港区")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("国立新美術館");
			text2.setVisibility(View.VISIBLE);
			text2.setText("東京タワー");
			text3.setVisibility(View.VISIBLE);
			text3.setText("六本木ヒルズ展望台　東京シティービュー");
			text4.setVisibility(View.VISIBLE);
			text4.setText("森美術館");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Library Lounge THESE");
			text6.setVisibility(View.VISIBLE);
			text6.setText("Rainy Day Bookstore & Cafe");
			text7.setVisibility(View.VISIBLE);
			text7.setText("TSUTAYA TOKYO ROPPOBNGI");
			text8.setVisibility(View.VISIBLE);
			text8.setText("汐留シオサイト5区イタリア街");
			text9.setVisibility(View.VISIBLE);
			text9.setText("赤坂サカス");
			text10.setVisibility(View.VISIBLE);
			text10.setText("Spiral Market");
			text11.setVisibility(View.VISIBLE);
			text11.setText("カレッタ汐留");
			text12.setVisibility(View.VISIBLE);
			text12.setText("cafe table TERRACE");
			text13.setVisibility(View.VISIBLE);
			text13.setText("STaiR");
			text14.setVisibility(View.VISIBLE);
			text14.setText("C’s fort");

		} else if (edit1.getText().toString().equals("港区 ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("汐留シオサイト5区イタリア街");
			text2.setVisibility(View.VISIBLE);
			text2.setText("赤坂サカス");
			text3.setVisibility(View.VISIBLE);
			text3.setText("カレッタ汐留");

		} else if (edit1.getText().toString().equals("港区 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Library Lounge THESE");
			text2.setVisibility(View.VISIBLE);
			text2.setText("Rainy Day Bookstore & Cafe");
			text3.setVisibility(View.VISIBLE);
			text3.setText("TSUTAYA TOKYO ROPPOBNGI");
			text4.setVisibility(View.VISIBLE);
			text4.setText("cafe table TERRACE");
			text5.setVisibility(View.VISIBLE);
			text5.setText("STaiR");
			text6.setVisibility(View.VISIBLE);
			text6.setText("C’s fort");

		} else if (edit1.getText().toString().equals("港区 美術館")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("国立新美術館");
			text2.setVisibility(View.VISIBLE);
			text2.setText("森美術館");

		} else if (edit1.getText().toString().equals("大阪")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("HEP FIVE");
			text2.setVisibility(View.VISIBLE);
			text2.setText("なんばパークス");
			text3.setVisibility(View.VISIBLE);
			text3.setText("アマーク　ド　パラディ");
			text4.setVisibility(View.VISIBLE);
			text4.setText("クレープリー　アルション");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Planet3rd");
			text6.setVisibility(View.VISIBLE);
			text6.setText("ベリーファンシー");
			text7.setVisibility(View.VISIBLE);
			text7.setText("北極星");
			text8.setVisibility(View.VISIBLE);
			text8.setText("COCOASHOP　AKAI TORI");
			text9.setVisibility(View.VISIBLE);
			text9.setText("リバーカフェ");
			text10.setVisibility(View.VISIBLE);
			text10.setText("太陽の塔");
			text11.setVisibility(View.VISIBLE);
			text11.setText("RIVER CAFE");
			text12.setVisibility(View.VISIBLE);
			text12.setText("ARABIYA");
			text13.setVisibility(View.VISIBLE);
			text13.setText("TABLES CAFE");
			text14.setVisibility(View.VISIBLE);
			text14.setText("和カフェyusoshi chano-ma なんばマルイ店");
			text15.setVisibility(View.VISIBLE);
			text15.setText("STANDARD BOOKSTORE");
			text16.setVisibility(View.VISIBLE);
			text16.setText("BUTTERFLY");
			text17.setVisibility(View.VISIBLE);
			text17.setText("野菜直売 Green Cafe");
			text18.setVisibility(View.VISIBLE);
			text18.setText("cafe The Plant Room");
			text19.setVisibility(View.VISIBLE);
			text19.setText("MINGUS");
			text20.setVisibility(View.VISIBLE);
			text20.setText("ANTICO CAFFE ALAVIS");
			text21.setVisibility(View.VISIBLE);
			text21.setText("LOBBY CAFE FASCINO");
			text22.setVisibility(View.VISIBLE);
			text22.setText("Anna Colors COFFEE");
			text23.setVisibility(View.VISIBLE);
			text23.setText("Cafe de la Paix");
			text24.setVisibility(View.VISIBLE);
			text24.setText("UMIYA CAFE westpoint");
			text25.setVisibility(View.VISIBLE);
			text25.setText("NOON+CAFE");
			text26.setVisibility(View.VISIBLE);
			text26.setText("Factory Cafe");
			text27.setVisibility(View.VISIBLE);
			text27.setText("WIRED CAFE 梅田NU chayamachi店");
			text28.setVisibility(View.VISIBLE);
			text28.setText("HANDS CAFE");
			text29.setVisibility(View.VISIBLE);
			text29.setText("ブラザーズカフェ 梅田オーパ店");
			text30.setVisibility(View.VISIBLE);
			text30.setText("The Grand Cafe");
			text31.setVisibility(View.VISIBLE);
			text31.setText("スーホルム カフェ+ダイニング");
			text32.setVisibility(View.VISIBLE);
			text32.setText("RIVER CAFE");
			text33.setVisibility(View.VISIBLE);
			text33.setText("雪ノ下工房");
			text34.setVisibility(View.VISIBLE);
			text34.setText("Marble");
			text35.setVisibility(View.VISIBLE);
			text35.setText("ノードカフェ");
			text36.setVisibility(View.VISIBLE);
			text36.setText("colors");
			text37.setVisibility(View.VISIBLE);
			text37.setText("PARTAGE");
			text38.setVisibility(View.VISIBLE);
			text38.setText("Cafeゆう 梅田店");
			text39.setVisibility(View.VISIBLE);
			text39.setText("Hug Cafe");
			text40.setVisibility(View.VISIBLE);
			text40.setText("美山cafe 梅三小路店");
			text41.setVisibility(View.VISIBLE);
			text41.setText("agmo on");
			text42.setVisibility(View.VISIBLE);
			text42.setText("トリトンカフェ 梅田店");
			text43.setVisibility(View.VISIBLE);
			text43.setText("J'adore Chayamachi");
			text44.setVisibility(View.VISIBLE);
			text44.setText("DOWNSTAIRS COFFEE");
			text45.setVisibility(View.VISIBLE);
			text45.setText("SOLVIVA");
			text46.setVisibility(View.VISIBLE);
			text46.setText("Monsoon Cafe");
			text47.setVisibility(View.VISIBLE);
			text47.setText("ツェープラス");
			text48.setVisibility(View.VISIBLE);
			text48.setText("国立国際美術館");
			text49.setVisibility(View.VISIBLE);
			text49.setText("あべの Q's MALL");
			text50.setVisibility(View.VISIBLE);
			text50.setText("梅田スカイビル");

		} else if (edit1.getText().toString().equals("大阪 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("アマーク　ド　パラディ");
			text2.setVisibility(View.VISIBLE);
			text2.setText("クレープリー　アルション");
			text3.setVisibility(View.VISIBLE);
			text3.setText("Planet3rd");
			text4.setVisibility(View.VISIBLE);
			text4.setText("ベリーファンシー");
			text5.setVisibility(View.VISIBLE);
			text5.setText("北極星");
			text6.setVisibility(View.VISIBLE);
			text6.setText("COCOASHOP　AKAI TORI");
			text7.setVisibility(View.VISIBLE);
			text7.setText("リバーカフェ");
			text8.setVisibility(View.VISIBLE);
			text8.setText("太陽の塔");
			text9.setVisibility(View.VISIBLE);
			text9.setText("RIVER CAFE");
			text10.setVisibility(View.VISIBLE);
			text10.setText("ARABIYA");
			text11.setVisibility(View.VISIBLE);
			text11.setText("TABLES CAFE");
			text12.setVisibility(View.VISIBLE);
			text12.setText("和カフェyusoshi chano-ma なんばマルイ店");
			text13.setVisibility(View.VISIBLE);
			text13.setText("STANDARD BOOKSTORE");
			text14.setVisibility(View.VISIBLE);
			text14.setText("BUTTERFLY");
			text15.setVisibility(View.VISIBLE);
			text15.setText("野菜直売 Green Cafe");
			text16.setVisibility(View.VISIBLE);
			text16.setText("cafe The Plant Room");
			text17.setVisibility(View.VISIBLE);
			text17.setText("MINGUS");
			text18.setVisibility(View.VISIBLE);
			text18.setText("ANTICO CAFFE ALAVIS");
			text19.setVisibility(View.VISIBLE);
			text19.setText("LOBBY CAFE FASCINO");
			text20.setVisibility(View.VISIBLE);
			text20.setText("Anna Colors COFFEE");
			text21.setVisibility(View.VISIBLE);
			text21.setText("Cafe de la Paix");
			text22.setVisibility(View.VISIBLE);
			text22.setText("UMIYA CAFE westpoint");
			text23.setVisibility(View.VISIBLE);
			text23.setText("NOON+CAFE");
			text24.setVisibility(View.VISIBLE);
			text24.setText("Factory Cafe");
			text25.setVisibility(View.VISIBLE);
			text25.setText("WIRED CAFE 梅田NU chayamachi店");
			text26.setVisibility(View.VISIBLE);
			text26.setText("HANDS CAFE");
			text27.setVisibility(View.VISIBLE);
			text27.setText("ブラザーズカフェ 梅田オーパ店");
			text28.setVisibility(View.VISIBLE);
			text28.setText("The Grand Cafe");
			text29.setVisibility(View.VISIBLE);
			text29.setText("スーホルム カフェ+ダイニング");
			text30.setVisibility(View.VISIBLE);
			text30.setText("RIVER CAFE");
			text31.setVisibility(View.VISIBLE);
			text31.setText("雪ノ下工房");
			text32.setVisibility(View.VISIBLE);
			text32.setText("Marble");
			text33.setVisibility(View.VISIBLE);
			text33.setText("ノードカフェ");
			text34.setVisibility(View.VISIBLE);
			text34.setText("colors");
			text35.setVisibility(View.VISIBLE);
			text35.setText("PARTAGE");
			text36.setVisibility(View.VISIBLE);
			text36.setText("Cafeゆう 梅田店");
			text37.setVisibility(View.VISIBLE);
			text37.setText("Hug Cafe");
			text38.setVisibility(View.VISIBLE);
			text38.setText("美山cafe 梅三小路店");
			text39.setVisibility(View.VISIBLE);
			text39.setText("agmo on");
			text40.setVisibility(View.VISIBLE);
			text40.setText("トリトンカフェ 梅田店");
			text41.setVisibility(View.VISIBLE);
			text41.setText("J'adore Chayamachi");
			text42.setVisibility(View.VISIBLE);
			text42.setText("DOWNSTAIRS COFFEE");
			text43.setVisibility(View.VISIBLE);
			text43.setText("SOLVIVA");
			text44.setVisibility(View.VISIBLE);
			text44.setText("Monsoon Cafe");
			text45.setVisibility(View.VISIBLE);
			text45.setText("ツェープラス");

		} else if (edit1.getText().toString().equals("大阪 ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("HEP FIVE");
			text2.setVisibility(View.VISIBLE);
			text2.setText("なんばパークス");
			text3.setVisibility(View.VISIBLE);
			text3.setText("あべの Q's MALL");

		} else if (edit1.getText().toString().equals("大阪 美術館")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("国立国際美術館");

		} else if (edit1.getText().toString().equals("梅田")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("HEP FIVE");
			text2.setVisibility(View.VISIBLE);
			text2.setText("梅田スカイビル");
			text3.setVisibility(View.VISIBLE);
			text3.setText("NOON+CAFE");
			text4.setVisibility(View.VISIBLE);
			text4.setText("Factory Cafe");
			text5.setVisibility(View.VISIBLE);
			text5.setText("WIRED CAFE 梅田NU chayamachi店");
			text6.setVisibility(View.VISIBLE);
			text6.setText("HANDS CAFE");
			text7.setVisibility(View.VISIBLE);
			text7.setText("ブラザーズカフェ 梅田オーパ店");
			text8.setVisibility(View.VISIBLE);
			text8.setText("The Grand Cafe");
			text9.setVisibility(View.VISIBLE);
			text9.setText("リバーカフェ");
			text10.setVisibility(View.VISIBLE);
			text10.setText("太陽の塔");
			text11.setVisibility(View.VISIBLE);
			text11.setText("RIVER CAFE");
			text12.setVisibility(View.VISIBLE);
			text12.setText("ARABIYA");
			text13.setVisibility(View.VISIBLE);
			text13.setText("TABLES CAFE");
			text14.setVisibility(View.VISIBLE);
			text14.setText("PARTAGE");
			text15.setVisibility(View.VISIBLE);
			text15.setText("Cafeゆう 梅田店");
			text16.setVisibility(View.VISIBLE);
			text16.setText("Hug Cafe");
			text17.setVisibility(View.VISIBLE);
			text17.setText("美山cafe 梅三小路店");
			text18.setVisibility(View.VISIBLE);
			text18.setText("agmo on");
			text19.setVisibility(View.VISIBLE);
			text19.setText("トリトンカフェ 梅田店");
			text20.setVisibility(View.VISIBLE);
			text20.setText("J'adore Chayamachi");
			text21.setVisibility(View.VISIBLE);
			text21.setText("DOWNSTAIRS COFFEE");
			text22.setVisibility(View.VISIBLE);
			text22.setText("SOLVIVA");
			text23.setVisibility(View.VISIBLE);
			text23.setText("Monsoon Cafe");
			text24.setVisibility(View.VISIBLE);
			text24.setText("ツェープラス");
			text25.setVisibility(View.VISIBLE);
			text25.setText("国立国際美術館");

		} else if (edit1.getText().toString().equals("梅田 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("NOON+CAFE");
			text2.setVisibility(View.VISIBLE);
			text2.setText("Factory Cafe");
			text3.setVisibility(View.VISIBLE);
			text3.setText("WIRED CAFE 梅田NU chayamachi店");
			text4.setVisibility(View.VISIBLE);
			text4.setText("HANDS CAFE");
			text5.setVisibility(View.VISIBLE);
			text5.setText("ブラザーズカフェ 梅田オーパ店");
			text6.setVisibility(View.VISIBLE);
			text6.setText("The Grand Cafe");
			text7.setVisibility(View.VISIBLE);
			text7.setText("リバーカフェ");
			text8.setVisibility(View.VISIBLE);
			text8.setText("太陽の塔");
			text9.setVisibility(View.VISIBLE);
			text9.setText("RIVER CAFE");
			text10.setVisibility(View.VISIBLE);
			text10.setText("ARABIYA");
			text11.setVisibility(View.VISIBLE);
			text11.setText("TABLES CAFE");
			text12.setVisibility(View.VISIBLE);
			text12.setText("PARTAGE");
			text13.setVisibility(View.VISIBLE);
			text13.setText("Cafeゆう 梅田店");
			text14.setVisibility(View.VISIBLE);
			text14.setText("Hug Cafe");
			text15.setVisibility(View.VISIBLE);
			text15.setText("美山cafe 梅三小路店");
			text16.setVisibility(View.VISIBLE);
			text16.setText("agmo on");
			text17.setVisibility(View.VISIBLE);
			text17.setText("トリトンカフェ 梅田店");
			text18.setVisibility(View.VISIBLE);
			text18.setText("J'adore Chayamachi");
			text19.setVisibility(View.VISIBLE);
			text19.setText("DOWNSTAIRS COFFEE");
			text20.setVisibility(View.VISIBLE);
			text20.setText("SOLVIVA");
			text21.setVisibility(View.VISIBLE);
			text21.setText("Monsoon Cafe");
			text22.setVisibility(View.VISIBLE);
			text22.setText("ツェープラス");

		} else if (edit1.getText().toString().equals("梅田 ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("HEP FIVE");

		} else if (edit1.getText().toString().equals("梅田 美術館")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("国立国際美術館");

		} else if (edit1.getText().toString().equals("心斎橋")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Planet3rd");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ベリーファンシー");
			text3.setVisibility(View.VISIBLE);
			text3.setText("北極星");
			text4.setVisibility(View.VISIBLE);
			text4.setText("COCOASHOP　AKAI TORI");
			text5.setVisibility(View.VISIBLE);
			text5.setText("TABLES CAFE");
			text6.setVisibility(View.VISIBLE);
			text6.setText("STANDARD BOOKSTORE");
			text7.setVisibility(View.VISIBLE);
			text7.setText("UMIYA CAFE westpoint");

		} else if (edit1.getText().toString().equals("心斎橋 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("Planet3rd");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ベリーファンシー");
			text3.setVisibility(View.VISIBLE);
			text3.setText("北極星");
			text4.setVisibility(View.VISIBLE);
			text4.setText("COCOASHOP　AKAI TORI");
			text5.setVisibility(View.VISIBLE);
			text5.setText("TABLES CAFE");
			text6.setVisibility(View.VISIBLE);
			text6.setText("STANDARD BOOKSTORE");
			text7.setVisibility(View.VISIBLE);
			text7.setText("UMIYA CAFE westpoint");

		} else if (edit1.getText().toString().equals("難波")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("クレープリー　アルション");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ARABIYA");
			text3.setVisibility(View.VISIBLE);
			text3.setText("和カフェyusoshi chano-ma なんばマルイ店");
			text4.setVisibility(View.VISIBLE);
			text4.setText("BUTTERFLY");
			text5.setVisibility(View.VISIBLE);
			text5.setText("cafe The Plant Room");
			text6.setVisibility(View.VISIBLE);
			text6.setText("MINGUS");
			text7.setVisibility(View.VISIBLE);
			text7.setText("ANTICO CAFFE ALAVIS");
			text8.setVisibility(View.VISIBLE);
			text8.setText("なんばパークス");
			text9.setVisibility(View.VISIBLE);
			text9.setText("LOBBY CAFE FASCINO");
			text10.setVisibility(View.VISIBLE);
			text10.setText("Cafe de la Paix");

		} else if (edit1.getText().toString().equals("難波 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("クレープリー　アルション");
			text2.setVisibility(View.VISIBLE);
			text2.setText("ARABIYA");
			text3.setVisibility(View.VISIBLE);
			text3.setText("和カフェyusoshi chano-ma なんばマルイ店");
			text4.setVisibility(View.VISIBLE);
			text4.setText("BUTTERFLY");
			text5.setVisibility(View.VISIBLE);
			text5.setText("cafe The Plant Room");
			text6.setVisibility(View.VISIBLE);
			text6.setText("MINGUS");
			text7.setVisibility(View.VISIBLE);
			text7.setText("ANTICO CAFFE ALAVIS");
			text8.setVisibility(View.VISIBLE);
			text8.setText("LOBBY CAFE FASCINO");
			text9.setVisibility(View.VISIBLE);
			text9.setText("Cafe de la Paix");

		} else if (edit1.getText().toString().equals("難波 ショッピングモール")) {

			text8.setVisibility(View.VISIBLE);
			text8.setText("なんばパークス");

		} else if (edit1.getText().toString().equals("天王寺")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("miss evans");
			text2.setVisibility(View.VISIBLE);
			text2.setText("DJANGO");
			text3.setVisibility(View.VISIBLE);
			text3.setText("j.s. pancake cafe");
			text4.setVisibility(View.VISIBLE);
			text4.setText("メゾンカイザー あべのハルカス近鉄本店 タワー館");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Oval");
			text6.setVisibility(View.VISIBLE);
			text6.setText("aureole d’ange");
			text7.setVisibility(View.VISIBLE);
			text7.setText("あべの Q's MALL");

		} else if (edit1.getText().toString().equals("天王寺 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("miss evans");
			text2.setVisibility(View.VISIBLE);
			text2.setText("DJANGO");
			text3.setVisibility(View.VISIBLE);
			text3.setText("j.s. pancake cafe");
			text4.setVisibility(View.VISIBLE);
			text4.setText("メゾンカイザー あべのハルカス近鉄本店 タワー館");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Oval");
			text6.setVisibility(View.VISIBLE);
			text6.setText("aureole d’ange");

		} else if (edit1.getText().toString().equals("天王寺 ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("あべの Q's MALL");

		} else if (edit1.getText().toString().equals("阿倍野")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("miss evans");
			text2.setVisibility(View.VISIBLE);
			text2.setText("DJANGO");
			text3.setVisibility(View.VISIBLE);
			text3.setText("j.s. pancake cafe");
			text4.setVisibility(View.VISIBLE);
			text4.setText("メゾンカイザー あべのハルカス近鉄本店 タワー館");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Oval");
			text6.setVisibility(View.VISIBLE);
			text6.setText("aureole d’ange");
			text7.setVisibility(View.VISIBLE);
			text7.setText("あべの Q's MALL");

		} else if (edit1.getText().toString().equals("阿倍野 カフェ")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("miss evans");
			text2.setVisibility(View.VISIBLE);
			text2.setText("DJANGO");
			text3.setVisibility(View.VISIBLE);
			text3.setText("j.s. pancake cafe");
			text4.setVisibility(View.VISIBLE);
			text4.setText("メゾンカイザー あべのハルカス近鉄本店 タワー館");
			text5.setVisibility(View.VISIBLE);
			text5.setText("Oval");
			text6.setVisibility(View.VISIBLE);
			text6.setText("aureole d’ange");

		} else if (edit1.getText().toString().equals("阿倍野 ショッピングモール")) {

			text1.setVisibility(View.VISIBLE);
			text1.setText("あべの Q's MALL");

		} else {

			text1.setVisibility(View.VISIBLE);
			text1.setText("該当なし。 スペースは半角で入力してください。");

		}
	}

	public void doAction(View v) {
		Intent intent1 = new Intent(MainMainActivity.this, MainActivity.class);
		startActivity(intent1);
	}
}
